
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManagerWebApi
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.Projects = new HashSet<Project>();

    }


    public int User_ID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int Employee_Id { get; set; }

    public Nullable<int> Project_ID { get; set; }

    public Nullable<int> Task_ID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Project> Projects { get; set; }

    public virtual Project Project { get; set; }

    public virtual Task Task { get; set; }

}

}
